# Copyright 2021 Leptopoda. All rights reserved.
# Use of this source code is governed by an APACHE-style license that can be
# found in the LICENSE file.

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
